---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  namespace: exercises
  name: stripprefix
spec:
  stripPrefix:
    prefixes:
      - /pingpong

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: exercises
  name: dwk-material-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: exercises-stripprefix@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: ping-pong
                port:
                  number: 1234
          - path: /
            pathType: Prefix
            backend:
              service:
                name: log-output
                port:
                  number: 2345
