apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: exercises
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: ykhaliuk/ping-pong
          env:
            - name: PORT
              value: "8080"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-config
                  key: postgres_db
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-config
                  key: postgres_port
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-config
                  key: postgres_url
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: postgres_password

